"""Add applicant profile

Revision ID: 70473366d659
Revises: 70473366d658
Create Date: 2026-03-12 20:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70473366d659'
down_revision: Union[str, None] = '70473366d658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('specialization', sa.Enum('PR', 'JOURNALISM', 'MEDIA_COM', 'MARKETING', 'SMM', name='specialization'), nullable=True),
    sa.Column('skill_level', sa.Enum('NOVICE', 'BEGINNER', 'CONFIDENT', 'ADVANCED', name='skilllevel'), nullable=True),
    sa.Column('employment_types', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('schedule_preferences', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('telegram', sa.String(), nullable=True),
    sa.Column('portfolio_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_applicant_profiles_id'), 'applicant_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applicant_profiles_id'), table_name='applicant_profiles')
    op.drop_table('applicant_profiles')
    # Cleanup Enums (optional but good practice for Postgres)
    sa.Enum(name='specialization').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='skilllevel').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
